# Generated by Django 2.1.3 on 2018-11-20 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineVoting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votefor',
            name='pages',
        ),
    ]
